baseURL: 'https://qcopendays.com'
languageCode: en-HK
title: Abandoned Website? Might as Well do Something
theme: vq
taxonomies:
Copyright: "&copy; 2022 Veriquiti Quo"
CopyrightLink: "https://instagram.com/veriquiti.quo"
params:
#  mainSections:
#    - regions
  assets:
    favicon: favicon.ico
    favicon16x16: favicon-16x16.png
    favicon32x32: favicon-32x32.png
    apple_touch_icon: apple-touch-icon.png
  disableThemeToggle: true
  disableScrollToTop: true
  ShowBreadCrumbs: true
  label:
    icon:
      - /media/veriquiti-quo-logo.png
    iconHeight: 40
    text: "Veriquiti Quo"
    doNotShowTitle: true
  env: production
  description: New with 2014-2020 past papers!
  images:
    - "/media/veriquiti-quo-logo.png"
  showReadingTime: true
  showgitinfo: true
menu:
  main:
    - name: Projects
      url: /projects/
    - name: Open Days
      url: /open-days/
enableGitInfo: true
markup:
  goldmark:
    parser:
      attribute:
        block: true